server.port=${PORT:8080}

bot.token=${TELEGRAM_TOKEN}
bot.username=${TELEGRAM_BOT_NAME}
admin-chat-id=${ADMIN_CHAT_ID}

# Logging
logging.level.root=INFO
logging.level.com.example.bot=INFO
logging.file.name=bot.log
logging.pattern.file=%d{HH:mm:ss} | %level | %message%n

